version: '3.8'
services:
  database:
    image: mysql:8.0
    container_name: test-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: oh-sense-test
      MYSQL_USER: admin
      MYSQL_PASSWORD: testpassword
    ports:
      - '3010:3306'
