name: Dev trigger

on:
  pull_request:
    branches:
      - dev
jobs:
  Dev-Testing:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.x

      - name: install dependencies
        run: npm i
      - name: Run Unit Test
        run: npm run test:report

      - name: Test Report
        id: test-report
        uses: dorny/test-reporter@v1.7.0
        if: success() || failure()
        with:
          name: test-results
          path: junit.xml
          fail-on-error: 'false'
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Discord noti
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_HOOK_URL }}
          status: ${{ job.status }}
          content: "There's a problem with your code. Check it out! <@492562319726084113>"
          title: 'Testing from ${{github.head_ref}}'
          color: 0xff0000
          url: '${{ steps.test-report.outputs.url_html }}'
          username: GitHub Actions Bot
          avatar_url: ${{ secrets.DISCORD_AVATAR_URL }}
          nocontext: true
          description: |
            **If you want to check the results of the test, click the link above**
            # [Triggered by ${{ github.actor }}]

            > ${{github.repository}}
